load("//google/protobuf:protobuf.bzl", "py_proto_library")

py_proto_library(
    name = "protocall_proto_pb2",
    srcs = ["protocall.proto"],
    default_runtime = "//google/protobuf:protobuf_python",
    protoc = "//google/protobuf:protoc",
    visibility = ["//visibility:public"],
)

# cc_proto_library(
#     name = "test_proto",
#     srcs = ["test.proto"],
# )

# py_proto_library(
#     name = "test_proto_pb2",
#     srcs = ["test.proto"],
# )
