py_binary(
    name = "protobuf_accessor",
    srcs = ["protobuf_accessor.py"],
    deps = [
        "//experimental/users/dek/protocall/proto:protocall_proto_pb2",
        "//experimental/users/dek/protocall/proto:test_proto_pb2",
        "//experimental/users/dek/protocall/proto/text_format_parser",
        "//third_party/py/pyparsing",
    ],
)
