py_binary(
    name = "protobuf_accessor",
    srcs = ["protobuf_accessor.py"],
    deps = [
        "//protocall/proto:protocall_proto_pb2",
        "//protocall/proto:test_proto_pb2",
        "//protocall/proto/text_format_parser",
        # "//third_party/py/pyparsing",
    ],
)
